# Generated by Django 4.1.5 on 2023-01-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
